remote: true
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: true
  associate: true
  mid_senior_level: true
  director: false
  executive: false

job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: true
  internship: false
  other: false
  volunteer: false

date:
  all_time: false
  month: false
  week: true
  24_hours: true

positions:
  - product manager
  - senior product manager
  - operations manager
  - operations engineer

locations:
  - USA
  - Canada

apply_once_at_company: true

distance: 100

company_blacklist:
  - Amazon

title_blacklist:
  - word1
  - word2

location_blacklist:
  - India

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 40

llm_model_type: openai
llm_model: 'gpt-4o-mini'
llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
